### ISSUE TITLE
Question about "Auto-commiting specific branches"

### ISSUE THREAD

**Issue by jsjoeio** [vsls-contrib/gitdoc#12]
How exactly does this differ from auto-committing? 

I see in the README

> In addition to enabling GitDoc during temporary periods, you can also choose to enable it on specific branches, in order to automatically track your work for as long as you're using the branch

What will the difference be?

Does this mean it won't use the intervals i.e. temporary periods?

Or does this simply mean instead of auto-committing happening for every branch, it's only on specific branches?

**Comment by lostintangent** [comment]
Closing this in favor of #14. The distinction between branch/non-branch enablement is confusing and so I'm going to remove this distinction from the product 😄
