### ISSUE TITLE
Workspace settings don't save to settings.json

### ISSUE THREAD

**Issue by jsjoeio** [vsls-contrib/gitdoc#13]
If I make changes to the Workspace with regard to GitDoc settings, shouldn't they save to my `.vscode/settings.json`? 

That's my naive assumption. If not, then feel free to disregard and close!

**Comment by lostintangent** [comment]
When you open the VS Code settings editor, you can choose where to save the changes: user/machine-level, or workspace-level. Extensions don't control this, and so as long as you select `Workspace` (see below), and then save your GitDoc settings, it should write them to `.vscode/settings.json`. Let me know if that doesn't work!

![image](https://user-images.githubusercontent.com/116461/89051155-acc4d000-d308-11ea-9b8a-3ba9414209c5.png)

**Comment by jsjoeio** [comment]
I must have been in User. Now it's working as expected! Thanks, Jonathan!
