### ISSUE TITLE
Commit date is the same for all commits (and wrong)

### ISSUE THREAD

**Issue by ashtom** [vsls-contrib/gitdoc#4]
Very cool extension, but somehow all commits have the exact same date. The generated commit message has the right time, but the commit timestamp is `Thu Apr 16 21:27:36 2020 -0700` for all commits. Example from [this repo](https://github.com/ashtom/about.me/commits/master):

```
commit b5c5231e9595f7eaa0c6bd57d1e2c040e89771ba (HEAD -> master, origin/master)
Author: Thomas Dohmke <SNIP>
Date:   Thu Apr 16 21:27:36 2020 -0700

    April 17, 2020 8:06 PM

commit 8975a3e7913ce4cbd451960856bf05e4aa2230c7
Author: Thomas Dohmke <SNIP>
Date:   Thu Apr 16 21:27:36 2020 -0700

    April 17, 2020 8:05 PM

commit 4eaf1dba1c81b1373d3836f742b5a41daa2702ae
Author: Thomas Dohmke <SNIP>
Date:   Thu Apr 16 21:27:36 2020 -0700

    April 17, 2020 8:05 PM

commit 47c89eedfb7fc95bf0ae955e41366afef5a23baa
Author: Thomas Dohmke <SNIP>
Date:   Thu Apr 16 21:27:36 2020 -0700

    April 17, 2020 8:04 PM
```

VSCode Info:

```
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by lostintangent** [comment]
@ashtom Hey! Thanks for reporting this. I didn’t notice this before, and. I think I know what’s happening 😁 I’ll try to get a fix out tonight!

**Comment by lostintangent** [comment]
This issue should now be fixed! If you update the `GitDoc` extension from the marketplace (`0.0.3`), the commit message and commit date should now match 👍 Please let me know if you run into any other problems. Thanks!
